POST  http://localhost:8080/auth HTTP/1.1
Content-Type: application/json

{
  "email": "admin@localhost",
  "password": "changeme"
}

###

GET http://localhost:8080/users HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkFsZXhhIFZlZ2EiLCJpYXQiOjE1MTYyMzkwMjJ9.vtxBvIP8Yyg-9gDI7SnPGGYhmW1PLOijKQ0NDtMP9Y8